apiVersion: apps/v1
kind: Deployment
metadata:
  name: documentation
spec:
  selector:
    matchLabels:
      app: documentation
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
    type: RollingUpdate
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: documentation
    spec:
      containers:
      - name: website
        image: docker.ausdertechnik.de/uitsmijter/websites/documentation
        ports:
        - containerPort: 80
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
          httpGet:
            path: /
            port: 80
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
          httpGet:
            path: /
            port: 80
        startupProbe:
          failureThreshold: 60
          periodSeconds: 5
          tcpSocket:
            port: 80

        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "20m"

      imagePullSecrets:
        - name: gitlab-auth
