baseURL = 'https://docs.uitsmijter.io/'
languageCode = 'en-us'
title = 'Uitsmijter Documentation'
theme = "uitsmijter"

pluralizeListTitles = false

# Required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Required if you want to render robots.txt template
enableRobotsTXT = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[taxonomies]
   tag = "tags"

