name: Main
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          GIT_HASH=$( git rev-parse --short HEAD )
          ./build.sh --tag ghcr.io/${{ github.repository_owner }}/documentation:latest
          docker tag ghcr.io/${{ github.repository_owner }}/documentation:latest ghcr.io/${{ github.repository_owner }}/documentation:${GIT_HASH}

      - name: push Docker images
        run:
          GIT_HASH=$( git rev-parse --short HEAD )
          docker push ghcr.io/${{ github.repository_owner }}/documentation:latest
          docker push ghcr.io/${{ github.repository_owner }}/documentation:${GIT_HASH}
