name: Main
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        shell: 'script -q -e -c "bash --noprofile --norc -eo pipefail {0}"'
        run: |
          GIT_HASH=$( git rev-parse --short HEAD )
          ./build.sh --tag ghcr.io/${{ github.repository_owner }}/documentation:latest
          docker tag ghcr.io/${{ github.repository_owner }}/documentation:latest ghcr.io/${{ github.repository_owner }}/documentation:${GIT_HASH}

      - name: push Docker images
        shell: bash
        run: |
          GIT_HASH=$( git rev-parse --short HEAD )
          docker push ghcr.io/${{ github.repository_owner }}/documentation:latest
          docker push ghcr.io/${{ github.repository_owner }}/documentation:${GIT_HASH}

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public

  # Notify
  notify_mattermost:
    name: Notify Mattermost
    permissions:
      contents: read
      statuses: read
      actions: read
      repository-projects: read
    needs:
      - build
    if: always()
    uses: uitsmijter/workflows/.github/workflows/builds-mattermost.yaml@main
    secrets:
      WEBHOOK: ${{ secrets.MATTERMOST_WEBHOOK_BUILD }}

  notify_mastodon:
    name: Notify Mastodon
    permissions:
      contents: read
      statuses: read
      actions: read
      repository-projects: read
    needs:
      - build
    if: always()
    uses: uitsmijter/workflows/.github/workflows/builds-mastodon.yaml@main
    secrets:
      MASTODON_URL: ${{ secrets.MASTODON_BUILDS_URL }}
      MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_BUILDS_TOKEN }}
